server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location /downloads/ {
    try_files $uri =404;
  }

  location /h5/assets/ {
    alias /usr/share/nginx/html/assets/;
    access_log off;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location = /h5 {
    try_files /index.html =404;
  }

  location /h5/ {
    try_files $uri /index.html;
  }

  location = /app {
    try_files /index.html =404;
  }

  location /app/ {
    try_files $uri /index.html;
  }

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok";
  }
}
