export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_MESSAGE_TYPE: 'INVALID_MESSAGE_TYPE',
  FILE_REJECTED: 'FILE_REJECTED'
} as const;

